//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Recorder.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDD_RECORDER_FORM               101
#define IDR_MAINFRAME                   128
#define IDR_RECORDTYPE                  129
#define IDD_DIALOG_WATCHDLG             130
#define IDD_DIALOG_BarEx                131
#define IDD_DIALOG_PopupRight           132
#define IDD_DIALOG_BGDLG                133
#define IDD_DIALOG_BarExBottomAcq       134
#define IDD_DIALOG_BarExBottomPlay      135
#define IDD_DIALOG_CheckCard            136
#define IDD_DIALOG_Measure              137
#define IDR_MENU_WatchDlgPopup          138
#define IDD_DIALOG_MeasureAdd           139
#define IDR_MENU_MeaDlgPopup            140
#define IDD_DIALOG_MeasureEdit          140
#define IDB_BMP_Close_Normal            141
#define IDD_DIALOG_Mark                 141
#define IDB_BMP_Minimize_Normal         142
#define IDD_DIALOG_Zoom                 142
#define IDC_CURSOR_ZoomIn               142
#define IDC_CURSOR_ZoomOut              143
#define IDD_DIALOG_StoragePath          143
#define IDB_BMP_Restore_Focus           144
#define IDC_CURSOR_ZoomDrag             144
#define IDB_BMP_Restore_Normal          145
#define IDC_CURSOR_MarkDragX            145
#define IDB_BMP_Minimize_Focus          146
#define IDC_CURSOR_MarkDragY            146
#define IDB_BMP_Close_Focus             147
#define IDC_CURSOR_ZoomRestore          147
#define IDB_BMP_MARK_X                  148
#define IDB_BMP_SCALE                   149
#define IDB_BMP_MARK_Y                  150
#define IDB_BMP_SCALE_BgGray            151
#define IDB_BMP_Play                    152
#define IDB_BMP_Pause                   153
#define IDB_BMP_SpeedUp                 154
#define IDB_BMP_SpeedDown               156
#define IDD_DIALOG_Save                 156
#define IDD_DIALOG_SaveAs               157
#define IDD_DIALOG_PopupProperty        158
#define IDB_BITMAP1                     158
#define IDD_DIALOG_ChSel                160
#define IDD_DIALOG_BarExTopChnSel       161
#define IDD_DIALOG_FftConf              162
#define IDC_STATIC_InitialMark          1002
#define IDC_STATIC_Title                1003
#define IDC_COMBO_RATE                  1004
#define IDC_COMBO_LENGTH                1005
#define IDC_SLIDER_TRIGGER_LEVEL        1006
#define IDC_STATIC_CursorRead           1007
#define IDC_SLIDER_TRIGGER_UpperLimit   1007
#define IDC_COMBO_TRIGGER_CHANNEL       1008
#define IDC_TAB1                        1008
#define IDC_TAB_BgDlg                   1008
#define IDC_COMBO_RANGE                 1009
#define IDC_BUTTON1                     1009
#define IDC_COMBO_TRIGGER_MODE          1010
#define IDC_BUTTON2                     1010
#define IDC_RADIO_Demo                  1010
#define IDC_BUTTON3                     1011
#define IDC_RADIO_PhyCard               1011
#define IDC_SLIDER_TRIGGER_LowerLimit   1011
#define IDC_LIST_PhyCard                1013
#define IDC_COMBO_DemoChn               1014
#define IDC_STATIC_TitleBar             1015
#define IDC_COMBO_MeaChannel            1016
#define IDC_COMBO_MeaType               1017
#define IDC_RADIO_Play                  1017
#define IDC_COMBO_MeaPart               1018
#define IDC_RADIO_Pause                 1018
#define IDC_STATIC_AcqStatus            1019
#define IDC_RADIO_OpenExistData         1020
#define IDC_EDIT_ExistDataPath          1021
#define IDC_BUTTON_Browse               1022
#define IDC_STATIC_TRIGGER_LEVEL        1023
#define IDC_RADIO_OverrideDoc           1024
#define IDC_STATIC_TRIGGER_UpperLimit   1024
#define IDC_RADIO_NewDoc                1025
#define IDC_STATIC_TRIGGER_LowerLimit   1025
#define IDC_EDIT_NewPath                1027
#define IDC_STATIC_WorkPlace            1028
#define IDC_BUTTON_SpeedUp              1029
#define IDC_BUTTON_SpeedDown            1030
#define IDC_COMBO_WavefForm             1031
#define IDC_COMBO_Frequency             1032
#define IDC_EDIT_AmpMax                 1033
#define IDC_EDIT_AmpMin                 1034
#define IDC_EDIT_SavePath               1034
#define IDC_COMBO_ChnIndex              1035
#define IDC_STATIC_Source               1035
#define IDC_STATIC_ChNum                1036
#define IDC_STATIC_SamplingRate         1037
#define IDC_STATIC_SamplingLen          1038
#define IDC_STATIC_SamplingTime         1039
#define IDC_STATIC_Range                1040
#define IDC_LIST_CH                     1041
#define IDC_STATIC_Tip                  1042
#define IDC_COMBO_ChnRange1             1043
#define IDC_COMBO_ChnRange2             1044
#define IDC_COMBO_ChnRange3             1045
#define IDC_COMBO_ChnRange4             1046
#define IDC_STATIC_ChnSel1              1047
#define IDC_STATIC_ChnSel2              1048
#define IDC_STATIC_ChnSel3              1049
#define IDC_STATIC_ChnSel4              1050
#define IDC_COMBO_FftBins               1051
#define IDC_COMBO_WindowMode            1052
#define IDC_COMBO_LogUnit               1053
#define IDC_EDIT_Impedance              1054
#define IDC_RADIO_Logarithm             1055
#define IDC_RADIO_Linear                1056
#define IDC_STATIC_Tips                 1057
#define ID_APP_CONNECT                  32771
#define ID_MENUITEM32772                32772
#define ID_EDIT_CopyText                32772
#define ID_MENUITEM32773                32773
#define ID_EDIT_CopySelectedImage       32773
#define ID_MENUITEM32774                32774
#define ID_LAYOUT_Mode1                 32775
#define ID_LAYOUT_Mode2                 32776
#define ID_LAYOUT_Mode3                 32777
#define ID_CTRL_StartAcq                32778
#define ID_CTRL_StopAcq                 32779
#define ID_LAYOUT_Mode4                 32780
#define ID_WATCH_NextPage               32791
#define ID_WATCH_PrePage                32792
#define ID_WATCH_Setting                32796
#define ID_WATCH_ZoomIn                 32797
#define ID_WATCH_ZoomOut                32798
#define ID_WATCH_None                   32799
#define ID_MENUITEM32801                32801
#define ID_MENUITEM32803                32803
#define ID_WATCH_ChSel                  32803
#define ID_MENUITEM32804                32804
#define ID_MENUITEM32806                32806
#define ID_MENUITEM32807                32807
#define ID_MENUITEM32809                32809
#define ID_MEA_ADDMEASURE               32810
#define ID_MEA_EDITMEASURE              32812
#define ID_MEA_DELMEASURE               32813
#define ID_WATCH_ZoomDrag               32814
#define ID_WATCH_ZoomReStore            32815
#define ID_APP_Help                     32816
#define ID_FILE_SAVE_Costum             32817
#define ID_FILE_SAVE_AS_Costum          32818
#define ID_WATCH_Property               32819
#define ID_WATCH_AddOsc                 32820
#define ID_WATCH_AddFreDomain           32821
#define ID_WATCH_RenameWatchDlg         32822
#define ID_WATCH_CloseWatchDlg          32823
#define ID_WATCH_FreqDomain             32825
#define ID_WATCH_TimeDomain             32826
#define ID_WATCH_FreqDomainConf         32829

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32830
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
